name: "CHTLAB Sleep Pad"
version: "1.0.0"
slug: "example_addon"
description: "An example add-on for Home Assistant"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "application"
boot: "auto"
options:
  api_token: ""
  username: ""
  password: ""
schema:
  api_token: str
  username: str
  password: str
devices:
  - "/dev/ttyS4:/dev/ttyS4:rwm"