name: "Example Add-on"
version: "1.0.0"
slug: "example_addon"
description: "An example add-on for Home Assistant"
arch:
  - amd64
  - armv7
  - armhf
  - i386
startup: "application"
boot: "auto"
options:
  api_token: ""
  username: ""
  password: ""
schema:
  api_token: str
  username: str
  password: str